version: "3"
services:
    db:
        image: mysql:5.7
        command: --disable-partition-engine-check
        ports:
            - '3306:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - /var/db_data:/var/lib/mysql
        networks:
            - backend
    dbtest:
        image: mysql:5.7
        command: --disable-partition-engine-check
        ports:
            - '3307:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE_TEST}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - /var/db_data_test:/var/lib/mysql
        networks:
            - backend
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        command: python3 manage.py runserver 0.0.0.0:8000
        environment:
            MYSQL_HOST: "${MYSQL_HOST}"
            MYSQL_HOST_TEST: "${MYSQL_HOST_TEST}"
            MYSQL_PORT: "${MYSQL_PORT}"
            MYSQL_PORT_TEST: "${MYSQL_PORT_TEST}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        networks:
            - backend
networks:
    backend:
