version: "3"
services:
    db:
        image: mysql:5.7
        command: --disable-partition-engine-check
        ports:
            - '3307:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: masterpw
            MYSQL_DATABASE: employees
            MYSQL_USER: reportinator
            MYSQL_PASSWORD: userpw
        volumes:
            - /var/db_data:/var/lib/mysql
        networks:
            - backend
    dbtest:
        image: mysql:5.7
        command: --disable-partition-engine-check
        ports:
            - '3307:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: masterpw
            MYSQL_DATABASE: test_employees
            MYSQL_USER: reportinator
            MYSQL_PASSWORD: userpw
        volumes:
            - /var/db_data_test:/var/lib/mysql
        networks:
            - backend
    seed:
        image: ubuntu
        environment:
            GIT_REPO: git clone https://github.com/datacharmer/test_db.git
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        command: python3 manage.py runserver 0.0.0.0:8000
        environment:
            MYSQL_HOST: db
            MYSQL_HOST_TEST: dbtest
            MYSQL_USER: reportinator
            MYSQL_PASSWORD: userpw
        volumes:
            - .:/code
        ports:
            - '8080:8000'
        networks:
            - backend
networks:
    backend:
